Repository dambem/ClimateMonitorV2, pull requests merged in 2020-08, with the labels that each got.

#120 Changing the colouring of the gauge to reflect pre-existing styling on page
  ClimateMonitorV2/public/javascripts/gauge.js
  ClimateMonitorV2/views/index.pug
Labels: Design Improvements, enhancement

#126 Move weather company API calls to backend
  ClimateMonitorV2/public/javascripts/new_mapping.js
  ClimateMonitorV2/routes/index.js
Labels: enhancement

#121 Initial python script checker
  .github/workflows/nodejs.yml
  .github/workflows/python.yml
  ClimateMonitorV2/package.json
  ClimateMonitorV2/public/files/data_getter.py
  ClimateMonitorV2/public/files/filegetter.py
  ClimateMonitorV2/public/files/full_time_display.py
  ClimateMonitorV2/public/files/graphmaker.py
  ClimateMonitorV2/public/files/requirements.txt
Labels: Optional, bug, test
