Repository dambem/ClimateMonitorV2, pull requests merged in 2020-07, with the labels that each got.

#72 Caroseled python graphs
  .gitignore
  ClimateMonitorV2/package-lock.json
  ClimateMonitorV2/package.json
  ClimateMonitorV2/public/files/PM2Full2020-04-26.png
  ClimateMonitorV2/public/files/data_getter.py
  ClimateMonitorV2/public/files/full_time_display.py
  ClimateMonitorV2/public/files/graphmaker.py
  ClimateMonitorV2/public/files/images/PM10Daily2019-10-30.png
  ClimateMonitorV2/public/files/images/PM10Daily2019-10-30highres.png
  ClimateMonitorV2/public/files/images/PM2Daily2019-06-24.png
  ClimateMonitorV2/public/files/images/PM2Daily2019-10-30.png
  ClimateMonitorV2/public/files/images/PM2Daily2020-02-17.png
  ClimateMonitorV2/public/files/images/PM2Daily2020-02-18.png
  ClimateMonitorV2/public/files/images/PM2Full2020-04-17.png
  ClimateMonitorV2/public/javascripts/config.js
  ClimateMonitorV2/public/javascripts/new_mapping.js
  ClimateMonitorV2/routes/index.js
  ClimateMonitorV2/views/index.pug
Labels: Design Improvements

#74 Carosuel url pointed to the wrong location
  ClimateMonitorV2/public/javascripts/new_mapping.js
Labels: Design Improvements, bug

#71 Huge improvement in detailed statistics
  ClimateMonitorV2/package-lock.json
  ClimateMonitorV2/package.json
  ClimateMonitorV2/public/javascripts/detailedstats.js
  ClimateMonitorV2/public/javascripts/new_mapping.js
  ClimateMonitorV2/public/sheffsense.png
  ClimateMonitorV2/routes/index.js
  ClimateMonitorV2/views/detailedstats.pug
  ClimateMonitorV2/views/index.pug
Labels: enhancement

#75 Animate people icons
  ClimateMonitorV2/public/javascripts/new_mapping.js
  ClimateMonitorV2/public/stylesheets/main.css
Labels: Design Improvements, enhancement

#77 Adds "breath" animation to infected people
  ClimateMonitorV2/public/javascripts/new_mapping.js
  ClimateMonitorV2/public/stylesheets/main.css
Labels: Design Improvements, enhancement

#78 Adding footer for urban flows
  ClimateMonitorV2/public/images/urbanflows.png
  ClimateMonitorV2/views/index.pug
Labels: Design Improvements, enhancement

#82 Sidebar setup and carosuel enhancements
  ClimateMonitorV2/public/github.png
  ClimateMonitorV2/public/javascripts/new_mapping.js
  ClimateMonitorV2/public/stylesheets/main.css
  ClimateMonitorV2/views/about.pug
  ClimateMonitorV2/views/detailedstats.pug
  ClimateMonitorV2/views/index.pug
  ClimateMonitorV2/views/layout.pug
Labels: Design Improvements, enhancement

#85 Dummy data for detailed statistics
  ClimateMonitorV2/public/javascripts/detailedstats.js
  ClimateMonitorV2/views/detailedstats.pug
Labels: Optional, enhancement

#89 Secretive codes
  .blackbox/.gitattributes
  .blackbox/blackbox-admins.txt
  .blackbox/blackbox-files.txt
  .blackbox/pubring.kbx
  .blackbox/trustdb.gpg
  .gitignore
  ClimateMonitorV2/public/javascripts/config.js
  ClimateMonitorV2/public/javascripts/config.js.gpg
  ClimateMonitorV2/public/javascripts/config.js~master
  PULL_REQUEST_TEMPLATE/BLACKBOX_PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Optional, bug, dependencies

#91 Initial addition of alt text
  ClimateMonitorV2/package-lock.json
  ClimateMonitorV2/public/javascripts/new_mapping.js
  ClimateMonitorV2/views/about.pug
  ClimateMonitorV2/views/detailedstats.pug
  ClimateMonitorV2/views/index.pug
  ClimateMonitorV2/views/layout.pug
Labels: Design Improvements, enhancement

#92 NEW ADMIN: meganw33@hotmail.com
  .blackbox/blackbox-admins.txt
  .blackbox/pubring.kbx
  .blackbox/trustdb.gpg
  .gitignore
  ClimateMonitorV2/public/javascripts/config.js.gpg
  README.md
Labels: blackbox

#94 Add npm encrypt and decrypt scripts
  ClimateMonitorV2/package.json
  README.md
Labels: blackbox, documentation, enhancement

#96 Update README.md
  README.md
Labels: documentation

#93 Add gauge to air quality index
  ClimateMonitorV2/public/javascripts/gauge.js
  ClimateMonitorV2/public/javascripts/new_mapping.js
  ClimateMonitorV2/public/stylesheets/main.css
  ClimateMonitorV2/views/index.pug
Labels: Design Improvements, enhancement

#90 Added front end tests:
  ClimateMonitorV2/test/frontendTests.js
Labels: enhancement, test

#97 light percentage change to sidebar to ensure it's more responsive
  ClimateMonitorV2/public/stylesheets/main.css
Labels: Design Improvements, bug

#103 Replace average pollution values with ones from the weather company
  ClimateMonitorV2/public/javascripts/new_mapping.js
  package-lock.json
Labels: enhancement

#106 This is the only way for me to get this work
  .blackbox/blackbox-admins.txt
  .blackbox/pubring.gpg
  .blackbox/secring.gpg
  ClimateMonitorV2/public/javascripts/config.js.gpg
Labels: blackbox

#108 Revert "This is the only way for me to get this work"
  .blackbox/blackbox-admins.txt
  .blackbox/pubring.gpg
  .blackbox/secring.gpg
  ClimateMonitorV2/public/javascripts/config.js.gpg
Labels: blackbox, bug

#110 Added myself to admin list
  .blackbox/blackbox-admins.txt
  .blackbox/pubring.kbx
  ClimateMonitorV2/public/javascripts/config.js.gpg
Labels: blackbox

#109 hot-fix, fixing detailed views
  ClimateMonitorV2/public/javascripts/backup_data.js
  ClimateMonitorV2/public/javascripts/detailedstats.js
  ClimateMonitorV2/public/javascripts/new_mapping.js
Labels: Design Improvements, bug

#104 Design updates
  ClimateMonitorV2/public/javascripts/new_mapping.js
  ClimateMonitorV2/public/stylesheets/main.css
  ClimateMonitorV2/views/about.pug
  ClimateMonitorV2/views/detailedstats.pug
  ClimateMonitorV2/views/index.pug
Labels: Design Improvements, enhancement

#115 Updated the About Page & added Our Team Page
  ClimateMonitorV2/public/icons/group.svg
  ClimateMonitorV2/public/icons/home.svg
  ClimateMonitorV2/public/icons/info.svg
  ClimateMonitorV2/public/icons/statistics.svg
  ClimateMonitorV2/public/images/akshat.png
  ClimateMonitorV2/public/images/alvaro.png
  ClimateMonitorV2/public/images/damian.png
  ClimateMonitorV2/public/images/harley.png
  ClimateMonitorV2/public/images/jonah.png
  ClimateMonitorV2/public/images/megan.png
  ClimateMonitorV2/public/images/morgan.png
  ClimateMonitorV2/public/stylesheets/main.css
  ClimateMonitorV2/routes/index.js
  ClimateMonitorV2/views/about.pug
  ClimateMonitorV2/views/detailedstats.pug
  ClimateMonitorV2/views/index.pug
  ClimateMonitorV2/views/our-team.pug
  ClimateMonitorV2/views/stylesheets/style.css
Labels: Design Improvements, documentation

#111 Just a check to stop the weird super high pollution values from coming in
  ClimateMonitorV2/public/javascripts/new_mapping.js
  ClimateMonitorV2/views/detailedstats.pug
  ClimateMonitorV2/views/index.pug
Labels: bug

#114 Remove blackbox
  .blackbox/.gitattributes
  .blackbox/blackbox-admins.txt
  .blackbox/blackbox-files.txt
  .blackbox/pubring.kbx
  .blackbox/trustdb.gpg
  ClimateMonitorV2/public/javascripts/config.js.gpg
  README.md
Labels: blackbox, bug

#119 Fix the sadly nobody would lose their lives
  ClimateMonitorV2/public/javascripts/new_mapping.js
Labels: bug
